/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/registro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar un usuario
         * @description Crea un usuario con rol SOCIO. La contraseña se persiste hasheada con bcrypt.
         */
        post: operations["registrarUsuario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar sesión */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/perfil": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener el perfil del usuario autenticado */
        get: operations["obtenerPerfil"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/disciplinas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar disciplinas
         * @description Público. Devuelve las disciplinas activas con su duración de turno.
         */
        get: operations["listarDisciplinas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/canchas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar canchas
         * @description Público. Devuelve las canchas activas. Con `incluirInactivas=true`
         *     devuelve también las dadas de baja y exige un token con rol ADMIN.
         */
        get: operations["listarCanchas"];
        put?: never;
        /**
         * Dar de alta una cancha
         * @description Requiere rol ADMIN. La cancha se crea activa.
         */
        post: operations["crearCancha"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/canchas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la cancha */
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Modificar una cancha
         * @description Requiere rol ADMIN. Solo se modifican los campos enviados.
         *
         *     `activa: false` da de baja la cancha: sale del catálogo y de la
         *     disponibilidad y no admite reservas nuevas, pero sus reservas
         *     existentes no cambian (RN-15). Un cambio de precio no modifica los
         *     montos de reservas ya creadas (RN-06).
         */
        patch: operations["actualizarCancha"];
        trace?: never;
    };
    "/equipamiento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar equipamiento
         * @description Público. Sin parámetros de fecha devuelve el catálogo activo con el
         *     stock total. Si se envían `fecha` y `horaInicio`, que van juntos, cada
         *     ítem incluye además el `stockDisponible` real para ese slot (RN-05).
         *
         *     Con `incluirInactivos=true` devuelve también los ítems dados de baja
         *     y exige un token con rol ADMIN.
         */
        get: operations["listarEquipamiento"];
        put?: never;
        /**
         * Dar de alta un ítem de equipamiento
         * @description Requiere rol ADMIN. El ítem se crea activo.
         */
        post: operations["crearEquipamiento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipamiento/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del ítem de equipamiento */
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Modificar un ítem de equipamiento
         * @description Requiere rol ADMIN. Solo se modifican los campos enviados.
         *
         *     `activo: false` da de baja el ítem: sale del catálogo y no se puede
         *     alquilar en reservas nuevas, pero las reservas que ya lo incluyen no
         *     cambian (RN-15). Reducir `stockTotal` tampoco modifica reservas
         *     existentes, y un cambio de precio no altera su `precioUnitario` (RN-06).
         */
        patch: operations["actualizarEquipamiento"];
        trace?: never;
    };
    "/disponibilidad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar disponibilidad de canchas
         * @description Público. Devuelve los slots libres de cada cancha para la fecha indicada.
         *
         *     La disponibilidad es un cálculo, no un registro almacenado: se generan
         *     los slots del horario de atención según la duración de turno de la
         *     disciplina y se restan los ocupados por reservas activas.
         */
        get: operations["consultarDisponibilidad"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar reservas
         * @description Requiere autenticación. Un SOCIO recibe únicamente sus propias reservas,
         *     aunque envíe el parámetro `clienteId` de otro usuario. Solo un ADMIN
         *     puede consultar reservas de terceros (RN-13).
         */
        get: operations["listarReservas"];
        put?: never;
        /**
         * Crear una reserva
         * @description Requiere rol SOCIO o ADMIN.
         *
         *     El identificador del cliente **no** viaja en el body: se toma del `sub`
         *     del JWT. El monto se calcula en el servidor a partir del precio de la
         *     cancha y queda congelado en la reserva (RN-06).
         *
         *     Tras confirmar la transacción se dispara un mail de confirmación.
         *     Un fallo en el envío no revierte la reserva (RN-14).
         */
        post: operations["crearReserva"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador interno de la reserva */
                id: number;
            };
            cookie?: never;
        };
        /**
         * Consultar el detalle de una reserva
         * @description Requiere autenticación. Si la reserva existe pero pertenece a otro
         *     usuario, se devuelve 404 en lugar de 403, para no permitir la
         *     enumeración de reservas ajenas (RN-13).
         */
        get: operations["obtenerReserva"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservas/{id}/cancelacion": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cancelar una reserva
         * @description Requiere autenticación. Marca la reserva como CANCELADA y libera el
         *     slot (RN-10). El registro nunca se elimina físicamente.
         *
         *     Un SOCIO solo puede cancelar hasta 2 horas antes del inicio (RN-04);
         *     un ADMIN no está sujeto a ese plazo.
         *
         *     Tras la cancelación se dispara el mail correspondiente (RN-14).
         */
        patch: operations["cancelarReserva"];
        trace?: never;
    };
    "/reservas/{id}/reenvio-mail": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reenviar el mail de una reserva
         * @description Requiere autenticación: lo pide el titular de la reserva o un ADMIN.
         *     Reenvía el mail que corresponde al estado actual: el de confirmación
         *     si la reserva está activa, o el de cancelación si está CANCELADA. El
         *     destinatario es siempre el titular.
         *
         *     Una reserva admite como máximo 3 reenvíos por hora (RN-16). Una falla
         *     del proveedor de mail no cambia la respuesta: queda registrada (RN-14).
         */
        post: operations["reenviarMailReserva"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/panel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar el panel del club
         * @description Requiere rol ADMIN. Resume la actividad de un día: reservas no
         *     canceladas del día y del anterior, facturación prevista, cancelaciones,
         *     ocupación y próximos turnos. Se calcula en cada consulta.
         *
         *     La ocupación es la cantidad de turnos con reserva no cancelada sobre
         *     los turnos que ofrecen las canchas activas según el horario de
         *     atención, como porcentaje entero redondeado.
         */
        get: operations["obtenerPanelAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enviar un mensaje de contacto
         * @description Público. Reenvía el mensaje por mail a la casilla del club.
         *
         *     Al ser un endpoint público que dispara envíos de mail, aplica rate
         *     limiting por IP (5 solicitudes por minuto) y valida un campo trampa
         *     anti-spam. Si ese campo viene completo, la respuesta es igualmente 202
         *     pero no se envía nada, para no darle señal al bot.
         */
        post: operations["enviarContacto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example SOCIO
         * @enum {string}
         */
        RolUsuario: "ADMIN" | "SOCIO";
        RegistroRequest: {
            /** @example Jeremías */
            nombre: string;
            /** @example Gómez */
            apellido: string;
            /**
             * Format: email
             * @example socio@club.com
             */
            email: string;
            /**
             * Format: password
             * @example unaClaveSegura123
             */
            password: string;
            /** @example +5493541000000 */
            telefono?: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example socio@club.com
             */
            email: string;
            /**
             * Format: password
             * @example unaClaveSegura123
             */
            password: string;
        };
        LoginResponse: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            accessToken: string;
            /**
             * @description Segundos de vigencia del token
             * @example 3600
             */
            expiraEn: number;
            usuario: components["schemas"]["Usuario"];
        };
        /** @description La contraseña nunca se expone en ninguna respuesta. */
        Usuario: {
            /** @example 42 */
            id: number;
            /** @example Jeremías */
            nombre: string;
            /** @example Gómez */
            apellido: string;
            /**
             * Format: email
             * @example socio@club.com
             */
            email: string;
            /** @example +5493541000000 */
            telefono?: string | null;
            rol: components["schemas"]["RolUsuario"];
        };
        Disciplina: {
            /** @example 1 */
            id: number;
            /** @example Pádel */
            nombre: string;
            /**
             * @description Duración del turno en minutos
             * @example 90
             */
            duracionTurnoMin: number;
            /** @example true */
            activa?: boolean;
        };
        Cancha: {
            /** @example 3 */
            id: number;
            /** @example Cancha 3 - Pádel */
            nombre: string;
            /** @example 1 */
            disciplinaId: number;
            /**
             * @description Nombre desnormalizado para evitar una consulta extra
             * @example Pádel
             */
            disciplina?: string;
            /** @example sintético */
            superficie?: string;
            /** @example true */
            techada?: boolean;
            /**
             * Format: double
             * @description Precio de un turno. No varía según la cantidad de jugadores.
             * @example 18000
             */
            precioPorTurno: number;
            /** @example true */
            activa?: boolean;
        };
        Equipamiento: {
            /** @example 7 */
            id: number;
            /** @example Paleta de pádel */
            nombre: string;
            /** @example 1 */
            disciplinaId: number;
            /** @example 6 */
            stockTotal: number;
            /**
             * @description Unidades libres en el slot consultado. Solo se incluye si la consulta
             *     envió `fecha` y `horaInicio` (RN-05).
             * @example 4
             */
            stockDisponible?: number | null;
            /**
             * Format: double
             * @example 2500
             */
            precioPorTurno: number;
            /** @example true */
            activo?: boolean;
        };
        CrearCanchaRequest: {
            /** @example 2 */
            disciplinaId: number;
            /** @example Pádel 4 */
            nombre: string;
            /** @example sintético */
            superficie?: string;
            /**
             * @default false
             * @example false
             */
            techada: boolean;
            /**
             * Format: double
             * @example 15000
             */
            precioPorTurno: number;
        };
        /** @description Todos los campos son opcionales; solo se modifican los enviados. */
        ActualizarCanchaRequest: {
            /** @example Pádel 4 */
            nombre?: string;
            /** @example sintético */
            superficie?: string | null;
            /** @example true */
            techada?: boolean;
            /**
             * Format: double
             * @example 16000
             */
            precioPorTurno?: number;
            /**
             * @description `false` da de baja la cancha sin tocar sus reservas (RN-15).
             * @example false
             */
            activa?: boolean;
        };
        CrearEquipamientoRequest: {
            /** @example 1 */
            disciplinaId: number;
            /** @example Visera */
            nombre: string;
            /** @example 8 */
            stockTotal: number;
            /**
             * Format: double
             * @example 1000
             */
            precioPorTurno: number;
        };
        /** @description Todos los campos son opcionales; solo se modifican los enviados. */
        ActualizarEquipamientoRequest: {
            /** @example Paleta de pádel */
            nombre?: string;
            /** @example 8 */
            stockTotal?: number;
            /**
             * Format: double
             * @example 3000
             */
            precioPorTurno?: number;
            /**
             * @description `false` da de baja el ítem sin tocar las reservas que lo incluyen (RN-15).
             * @example false
             */
            activo?: boolean;
        };
        SlotDisponible: {
            /** @example 19:00 */
            horaInicio: string;
            /** @example 20:30 */
            horaFin: string;
        };
        DisponibilidadCancha: {
            /** @example 3 */
            canchaId: number;
            /** @example Cancha 3 - Pádel */
            nombre: string;
            /** @example Pádel */
            disciplina?: string;
            /**
             * Format: double
             * @example 18000
             */
            precioPorTurno: number;
            slots: components["schemas"]["SlotDisponible"][];
        };
        DisponibilidadResponse: {
            /**
             * Format: date
             * @example 2026-09-15
             */
            fecha: string;
            canchas: components["schemas"]["DisponibilidadCancha"][];
        };
        ItemEquipamientoRequest: {
            /** @example 7 */
            equipamientoId: number;
            /** @example 2 */
            cantidad: number;
        };
        /**
         * @description El identificador del cliente no forma parte del body. Se resuelve
         *     a partir del JWT, de modo que un usuario no pueda reservar a nombre de otro.
         */
        CrearReservaRequest: {
            /** @example 3 */
            canchaId: number;
            /**
             * Format: date
             * @example 2026-09-15
             */
            fecha: string;
            /**
             * @description Hora de inicio del slot. La hora de fin la calcula el servidor
             *     a partir de la duración de turno de la disciplina.
             * @example 19:00
             */
            horaInicio: string;
            /**
             * @description Opcional. No afecta el precio: un turno cuesta lo mismo con 2 que
             *     con 4 jugadores. Sirve para que el club sepa cuánta gente espera.
             * @example 4
             */
            cantidadJugadores?: number;
            /** @description Ítems a alquilar. Opcional. */
            equipamiento?: components["schemas"]["ItemEquipamientoRequest"][];
        };
        CancelarReservaRequest: {
            /** @example Se suspendió por lluvia */
            motivo?: string;
        };
        ItemEquipamientoReserva: {
            /** @example 7 */
            equipamientoId: number;
            /** @example Paleta de pádel */
            nombre: string;
            /** @example 2 */
            cantidad: number;
            /**
             * Format: double
             * @description Precio congelado al momento de crear la reserva (RN-06)
             * @example 2500
             */
            precioUnitario: number;
            /**
             * Format: double
             * @example 5000
             */
            subtotal: number;
        };
        /**
         * @example CONFIRMADA
         * @enum {string}
         */
        EstadoReserva: "CONFIRMADA" | "CANCELADA" | "COMPLETADA";
        Reserva: {
            /** @example 128 */
            id: number;
            /**
             * @description Código legible para el cliente
             * @example RES-A7F3K2
             */
            codigo: string;
            /** @example 42 */
            clienteId: number;
            /**
             * @description Nombre y apellido del titular de la reserva
             * @example Jeremías Gómez
             */
            cliente?: string;
            /** @example 3 */
            canchaId: number;
            /** @example Cancha 3 - Pádel */
            cancha?: string;
            /**
             * Format: date
             * @example 2026-09-15
             */
            fecha: string;
            /** @example 19:00 */
            horaInicio: string;
            /** @example 20:30 */
            horaFin: string;
            /** @example 4 */
            cantidadJugadores?: number | null;
            estado: components["schemas"]["EstadoReserva"];
            equipamiento?: components["schemas"]["ItemEquipamientoReserva"][];
            /**
             * Format: double
             * @description Precio de la cancha congelado al crear la reserva (RN-06)
             * @example 24000
             */
            montoCancha?: number;
            /**
             * Format: double
             * @example 5000
             */
            montoEquipamiento?: number;
            /**
             * Format: double
             * @example 29000
             */
            montoTotal: number;
            /**
             * Format: date-time
             * @example 2026-09-01T14:32:10Z
             */
            creadaEn?: string;
            /**
             * Format: date-time
             * @example null
             */
            canceladaEn?: string | null;
            /** @example null */
            motivoCancelacion?: string | null;
        };
        /**
         * @example CONFIRMACION
         * @enum {string}
         */
        TipoNotificacion: "CONFIRMACION" | "CANCELACION";
        ReenvioMailResponse: {
            /** @example Te reenviamos el mail de tu reserva. */
            mensaje: string;
            tipo: components["schemas"]["TipoNotificacion"];
            /**
             * Format: email
             * @description Mail del titular, que recibe el reenvío aunque lo pida un ADMIN
             * @example socio@club.com
             */
            destinatario: string;
        };
        OcupacionCancha: {
            /** @example 3 */
            canchaId: number;
            /** @example Pádel 1 */
            nombre: string;
            /** @example Pádel */
            disciplina: string;
            /**
             * @description Ocupación de la cancha en los 7 días que terminan en la fecha consultada
             * @example 82
             */
            porcentaje: number;
        };
        ProximoTurno: {
            /** @example 128 */
            reservaId: number;
            /** @example 20:00 */
            horaInicio: string;
            /** @example Pádel 1 */
            cancha: string;
            /** @example Pádel */
            disciplina: string;
            /**
             * @description Nombre y apellido del titular
             * @example Jeremías Gómez
             */
            cliente: string;
            /** @example 4 */
            cantidadJugadores?: number | null;
        };
        PanelAdmin: {
            /**
             * Format: date
             * @example 2026-09-15
             */
            fecha: string;
            /**
             * @description Reservas no canceladas cuyo turno es en la fecha consultada
             * @example 14
             */
            reservasDelDia: number;
            /**
             * @description Lo mismo para el día anterior
             * @example 11
             */
            reservasDiaAnterior: number;
            /**
             * Format: double
             * @description Suma de `montoTotal` de las reservas no canceladas del día, a cobrar en el club
             * @example 186000
             */
            facturacionPrevista: number;
            /**
             * @description Reservas canceladas ese día, según la fecha local de la cancelación
             * @example 2
             */
            cancelacionesDelDia: number;
            /**
             * @description Cuántas de esas cancelaciones se hicieron con la anticipación mínima (RN-04)
             * @example 2
             */
            cancelacionesDentroDelPlazo: number;
            /**
             * @description Porcentaje entero de turnos ocupados en la fecha consultada
             * @example 68
             */
            ocupacionDelDia: number;
            /**
             * @description Porcentaje entero de turnos ocupados en los 7 días que terminan en la fecha consultada
             * @example 61
             */
            ocupacionPromedioSemanal: number;
            /** @description Una entrada por cancha activa */
            ocupacionPorCancha: components["schemas"]["OcupacionCancha"][];
            /**
             * @description Reservas no canceladas de la fecha, ordenadas por hora de inicio.
             *     Si la fecha es hoy, solo las que todavía no empezaron.
             */
            proximosTurnos: components["schemas"]["ProximoTurno"][];
        };
        ContactoRequest: {
            /** @example Ana Fernández */
            nombre: string;
            /**
             * Format: email
             * @example ana@example.com
             */
            email: string;
            /** @example +5493541000000 */
            telefono?: string | null;
            /** @example Hola, quería consultar por el alquiler de canchas para un torneo interno. */
            mensaje: string;
            /**
             * @description Campo trampa anti-spam. No se muestra al usuario y debe llegar vacío.
             *     Si viene completo, la solicitud se descarta en silencio.
             * @example
             */
            sitioWeb?: string;
        };
        ContactoResponse: {
            /** @example Recibimos tu consulta. Te respondemos dentro de las 48 horas. */
            mensaje: string;
        };
        Error: {
            /**
             * @description Identificador legible del tipo de error
             * @example SLOT_NO_DISPONIBLE
             */
            tipo: string;
            /**
             * @description Descripción breve, apta para mostrar al usuario
             * @example El horario solicitado ya está reservado
             */
            titulo: string;
            /**
             * @description Código de estado HTTP
             * @example 409
             */
            estado: number;
            /**
             * @description Explicación específica de esta ocurrencia
             * @example La cancha 3 ya tiene una reserva activa el 2026-09-15 a las 19:00.
             */
            detalle?: string;
            /**
             * @description Ruta donde ocurrió el error
             * @example /reservas
             */
            instancia?: string;
        };
    };
    responses: {
        /** @description Parámetros ausentes o mal formados */
        SolicitudInvalida: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Falta el token, está vencido o es inválido */
        NoAutenticado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "tipo": "NO_AUTENTICADO",
                 *       "titulo": "Se requiere autenticación",
                 *       "estado": 401,
                 *       "detalle": "El token no fue enviado o ya expiró.",
                 *       "instancia": "/reservas"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Autenticado pero sin permisos para la operación */
        SinPermisos: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description El recurso no existe, o existe pero no pertenece al usuario autenticado (RN-13) */
        NoEncontrado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description La solicitud es sintácticamente válida pero incumple una regla de negocio
         *     (fecha pasada, horizonte excedido, horario fuera de la grilla de turnos,
         *     límite de reservas activas, equipamiento de otra disciplina, plazo de
         *     cancelación vencido).
         */
        ReglaDeNegocioViolada: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registrarUsuario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistroRequest"];
            };
        };
        responses: {
            /** @description Usuario creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usuario"];
                };
            };
            400: components["responses"]["SolicitudInvalida"];
            /** @description Ya existe un usuario con ese mail */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Autenticación correcta */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["SolicitudInvalida"];
            /**
             * @description Credenciales inválidas. El mensaje es genérico a propósito:
             *     no debe revelar si el mail existe en el sistema.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    obtenerPerfil: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Datos del usuario */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usuario"];
                };
            };
            401: components["responses"]["NoAutenticado"];
        };
    };
    listarDisciplinas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de disciplinas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Disciplina"][];
                };
            };
        };
    };
    listarCanchas: {
        parameters: {
            query?: {
                disciplinaId?: number;
                techada?: boolean;
                /** @description Solo ADMIN. Incluye las canchas dadas de baja. */
                incluirInactivas?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de canchas. Puede ser vacío si ningún filtro coincide. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cancha"][];
                };
            };
            400: components["responses"]["SolicitudInvalida"];
            401: components["responses"]["NoAutenticado"];
            403: components["responses"]["SinPermisos"];
        };
    };
    crearCancha: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearCanchaRequest"];
            };
        };
        responses: {
            /** @description Cancha creada */
            201: {
                headers: {
                    /**
                     * @description URI del recurso creado
                     * @example /api/v1/canchas/7
                     */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cancha"];
                };
            };
            400: components["responses"]["SolicitudInvalida"];
            401: components["responses"]["NoAutenticado"];
            403: components["responses"]["SinPermisos"];
            404: components["responses"]["NoEncontrado"];
        };
    };
    actualizarCancha: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la cancha */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarCanchaRequest"];
            };
        };
        responses: {
            /** @description Cancha modificada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cancha"];
                };
            };
            400: components["responses"]["SolicitudInvalida"];
            401: components["responses"]["NoAutenticado"];
            403: components["responses"]["SinPermisos"];
            404: components["responses"]["NoEncontrado"];
        };
    };
    listarEquipamiento: {
        parameters: {
            query?: {
                disciplinaId?: number;
                /** @example 2026-09-15 */
                fecha?: string;
                /** @example 20:00 */
                horaInicio?: string;
                /** @description Solo ADMIN. Incluye los ítems dados de baja. */
                incluirInactivos?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de equipamiento */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Equipamiento"][];
                };
            };
            400: components["responses"]["SolicitudInvalida"];
            401: components["responses"]["NoAutenticado"];
            403: components["responses"]["SinPermisos"];
        };
    };
    crearEquipamiento: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearEquipamientoRequest"];
            };
        };
        responses: {
            /** @description Ítem creado */
            201: {
                headers: {
                    /**
                     * @description URI del recurso creado
                     * @example /api/v1/equipamiento/8
                     */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Equipamiento"];
                };
            };
            400: components["responses"]["SolicitudInvalida"];
            401: components["responses"]["NoAutenticado"];
            403: components["responses"]["SinPermisos"];
            404: components["responses"]["NoEncontrado"];
        };
    };
    actualizarEquipamiento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del ítem de equipamiento */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarEquipamientoRequest"];
            };
        };
        responses: {
            /** @description Ítem modificado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Equipamiento"];
                };
            };
            400: components["responses"]["SolicitudInvalida"];
            401: components["responses"]["NoAutenticado"];
            403: components["responses"]["SinPermisos"];
            404: components["responses"]["NoEncontrado"];
        };
    };
    consultarDisponibilidad: {
        parameters: {
            query: {
                /** @example 2026-09-15 */
                fecha: string;
                disciplinaId?: number;
                canchaId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disponibilidad de la fecha consultada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisponibilidadResponse"];
                };
            };
            400: components["responses"]["SolicitudInvalida"];
        };
    };
    listarReservas: {
        parameters: {
            query?: {
                /** @description Solo tiene efecto para usuarios con rol ADMIN. */
                clienteId?: number;
                fecha?: string;
                estado?: components["schemas"]["EstadoReserva"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de reservas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reserva"][];
                };
            };
            400: components["responses"]["SolicitudInvalida"];
            401: components["responses"]["NoAutenticado"];
        };
    };
    crearReserva: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearReservaRequest"];
            };
        };
        responses: {
            /** @description Reserva creada */
            201: {
                headers: {
                    /**
                     * @description URI del recurso creado
                     * @example /api/v1/reservas/128
                     */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reserva"];
                };
            };
            400: components["responses"]["SolicitudInvalida"];
            401: components["responses"]["NoAutenticado"];
            403: components["responses"]["SinPermisos"];
            404: components["responses"]["NoEncontrado"];
            /**
             * @description Conflicto de estado. El slot ya está reservado (RN-01)
             *     o no hay stock suficiente de equipamiento en ese slot (RN-05).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ReglaDeNegocioViolada"];
        };
    };
    obtenerReserva: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador interno de la reserva */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalle de la reserva, incluido el desglose de equipamiento */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reserva"];
                };
            };
            401: components["responses"]["NoAutenticado"];
            404: components["responses"]["NoEncontrado"];
        };
    };
    cancelarReserva: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CancelarReservaRequest"];
            };
        };
        responses: {
            /** @description Reserva cancelada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reserva"];
                };
            };
            401: components["responses"]["NoAutenticado"];
            404: components["responses"]["NoEncontrado"];
            /** @description La reserva no se puede cancelar porque ya está cancelada o su turno ya terminó */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "tipo": "RESERVA_NO_CANCELABLE",
                     *       "titulo": "Esta reserva ya no se puede cancelar",
                     *       "estado": 409,
                     *       "detalle": "La reserva RES-A7F3K2 ya está cancelada.",
                     *       "instancia": "/reservas/128/cancelacion"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ReglaDeNegocioViolada"];
        };
    };
    reenviarMailReserva: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reenvío aceptado */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReenvioMailResponse"];
                };
            };
            401: components["responses"]["NoAutenticado"];
            404: components["responses"]["NoEncontrado"];
            /** @description La reserva ya se jugó y no admite reenvío */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "tipo": "REENVIO_NO_DISPONIBLE",
                     *       "titulo": "No hay mail para reenviar",
                     *       "estado": 409,
                     *       "detalle": "El turno de la reserva RES-A7F3K2 ya terminó.",
                     *       "instancia": "/reservas/128/reenvio-mail"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Se alcanzó el límite de reenvíos de la reserva */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "tipo": "DEMASIADAS_SOLICITUDES",
                     *       "titulo": "Ya reenviamos este mail varias veces",
                     *       "estado": 429,
                     *       "detalle": "Se admiten hasta 3 reenvíos por hora. Volvé a intentar más tarde.",
                     *       "instancia": "/reservas/128/reenvio-mail"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    obtenerPanelAdmin: {
        parameters: {
            query?: {
                /**
                 * @description Día a consultar. Por defecto, hoy en la hora local del club.
                 * @example 2026-09-15
                 */
                fecha?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Panel del día consultado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PanelAdmin"];
                };
            };
            400: components["responses"]["SolicitudInvalida"];
            401: components["responses"]["NoAutenticado"];
            403: components["responses"]["SinPermisos"];
        };
    };
    enviarContacto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactoRequest"];
            };
        };
        responses: {
            /** @description Mensaje aceptado para su envío */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactoResponse"];
                };
            };
            400: components["responses"]["SolicitudInvalida"];
            /** @description Demasiadas solicitudes desde la misma IP */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "tipo": "DEMASIADAS_SOLICITUDES",
                     *       "titulo": "Superaste el límite de mensajes",
                     *       "estado": 429,
                     *       "detalle": "Se admiten hasta 5 mensajes por minuto. Volvé a intentar en un rato.",
                     *       "instancia": "/contacto"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
